confirmLink的el-dialog使用class替换cutsom-class.
ElementPlusError: [el-dialog] [Attribute] custom-class is about to be
deprecated in version 2.3.0, please use class instead.
For more detail, please visit:
https://element-plus.org/en-US/component/dialog.html#attributes